
# MODEL META UB - LGBM - PDV
config_lgbm:
  TARGET: FRAUD_FLAG
  WEIGHT: WEIGHT
  FEATURES:
    - 'COMPUTERS'
    - 'TELEPHONES FAX MACHINES TWOWAY RADIOS'
    - 'AUDIO ACCESSORIES'
    - 'COMPUTER PERIPHERALS ACCESSORIES'
    - 'TELEVISIONS HOME CINEMA'
  categorical_features:
  seed: 1111
  n_splits: 5
  parameters:
    objective: binary
    metric: binary_logloss
    max_depth: 7
    min_data_in_leaf: 10
    colsample_bytree: 0.8
    subsample: 0.8
    learning_rate: 0.005
    boosting_type: "gbdt"
    num_iteration: 3000
    lambda_l1 : 1.5
    n_jobs: -1
    verbose : -1
